extra:
  
  cloudfront:
    labels: {}
    annotations: {}
    domainName: https://www.example.com
    lbDomainName: https://www.example.com
    originId: "LoadBalancer"
    httpPort: 80
    httpsPort: 443
    originProtocolPolicy: "https-only"
    originSSLProtocols: 
      items: ["TLSv1.2"]
    viewerProtocolPolicy: "redirect-to-https"
    minTTL: 1000
    allowedMethods: 
      - "GET"
      - "HEAD"
      - "OPTIONS"
      - "PUT"
      - "POST"
      - "PATCH"
      - "DELETE"
    cachedMethods: 
      - "GET"
      - "HEAD"
    comment: ""
    forwardedValues:
      headers:
        - X-Forwarded-For
        - X-Forwarded-Proto
        - X-Forwarded-Port

  certificate:
    enable: true
    name: certificate
    labels: {}
    annotations: {}
    commonName: ""
    dnsNames: []
    duration: 2160h
    renewBefore: 360h
    issuerRef:
      kind: ClusterIssuer
      name: issuer