extra:
  service:
    enable: true
    labels: {}
    annotations: {}
    loadBalancerClass: "service.k8s.aws/nlb"
  
  prometheus:
    enable: true
    labels: {}
    annotations: {}
  
  certificate:
    enable: true
    name: certificate
    labels: {}
    annotations: {}
    commonName: ""
    dnsNames: []
    duration: 2160h
    renewBefore: 360h
    issuerRef:
      kind: ClusterIssuer
      name: issuer
  
  secrets:
    refreshInterval: 1h0m0s
    refreshPolicy: Periodic
    secretArn: arn:aws:secretsmanager:us-east-1:123456789012:secret:coder-abc123

  secretStore:
    labels: {}
    annotations: {}
    aws:
      region: us-east-1
