apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ctrl-role
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extra.sa.controller.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.extra.sa.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-node-role
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extra.sa.node.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.extra.sa.node.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}