apiVersion: acm.services.k8s.aws/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.extra.certificate.name }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.extra.certificate.labels }}
  labels:
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.extra.certificate.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  privateKey:
    name: {{ .Values.extra.certificate.name }}
    namespace: {{ .Release.Namespace }}
    key: tls.key
  certificate:
    name: {{ .Values.extra.certificate.name }}
    namespace: {{ .Release.Namespace }}
    key: tls.crt
---
{{- if .Values.extra.certificate.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.extra.certificate.name }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.extra.certificate.labels }}
  labels:
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.extra.certificate.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec: 
  commonName: {{ .Values.extra.certificate.commonName | quote }}
  dnsNames:
{{ toYaml .Values.extra.certificate.dnsNames | nindent 4 }}
  duration: {{ .Values.extra.certificate.duration | quote }}
  renewBefore: {{ .Values.extra.certificate.renewBefore | quote }}
  issuerRef:
    kind: {{ .Values.extra.certificate.issuerRef.kind }}
    name: {{ .Values.extra.certificate.issuerRef.name }}
  secretName: {{ .Values.extra.certificate.name }}
  privateKey:
    rotationPolicy: Never
    algorithm: RSA
    encoding: PKCS1
    size: 2048
{{- end }}