---
{{- if not .Values.coder.serviceAccount.disableCreate }}
{{ include "libcoder.serviceaccount" (list . "coder.serviceaccount") }}
{{- end }}

---
{{ include "libcoder.statefulset" (list . "coder.statefulset") }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coder.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "coder.selectorLabels" . | nindent 4 }}