apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}.aws
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extra.secretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.extra.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.extra.secretStore.aws.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}.secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}.aws
    kind: SecretStore
  refreshPolicy: {{ .Values.extra.secrets.refreshPolicy }}
  refreshInterval: {{ .Values.extra.secrets.refreshInterval }}
  target:
    name: {{ .Release.Name }}.secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.extra.secrets.secretArn }}