{{- if .Values.extra.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extra.service.labels }}
  labels:
    {{- toYaml . | nindent 4}}
  {{- end}}
  {{- with .Values.extra.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  type: LoadBalancer
  loadBalancerClass: {{ .Values.extra.service.loadBalancerClass }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    "app.kubernetes.io/instance": coder
    "app.kubernetes.io/name": {{ .Release.Name }}
{{- end }}
---
{{- if .Values.extra.prometheus.enable }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extra.prometheus.labels }}
  labels:
    {{- toYaml . | nindent 4}}
  {{- end}}
  {{- with .Values.extra.prometheus.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    "app.kubernetes.io/instance": coder
    "app.kubernetes.io/name": {{ .Release.Name }}
{{- end }}