{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default" | quote }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    "helm.sh/hook": post-install,post-upgrade
  {{- end }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: {{ .provisioner }}
volumeBindingMode: {{ .volumeBindingMode | default "WaitForFirstConsumer" | quote }}
allowVolumeExpansion: {{ .allowVolumeExpansion | default true }}
{{- with .allowedTopologies }}
allowedTopologies:
  {{- toYaml . | nindent 2}}
{{- end }}
{{- with .parameters }}
parameters:
  {{- toYaml . | nindent 2}}
{{- end }}
{{- end }}