{
 "title": "Coder AI Bridge",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "username",
    "query": "select username from users where deleted=false;"
   },
   {
    "name": "provider",
    "query": "SELECT DISTINCT provider FROM aibridge_interceptions WHERE provider IS NOT NULL ORDER BY 1;"
   },
   {
    "name": "model",
    "query": "SELECT DISTINCT model FROM aibridge_interceptions WHERE model IS NOT NULL AND provider ~ '$${provider:regex}' ORDER BY 1;"
   }
  ]
 },
 "panels": [
  { "title": "Usage leaderboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Leaderboard per user",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select u.username, sum(t.input_tokens) as input,\nsum(t.output_tokens) as output,\nsum(\n  COALESCE(\n    t.metadata->>'cache_read_input', -- Anthropic\n    t.metadata->>'prompt_cached'     -- OpenAI\n  )::int\n) AS cache_read_input,\nsum((t.metadata->>'cache_creation_input')::int) AS cache_creation_input -- Anthropic\nfrom aibridge_token_usages t\njoin aibridge_interceptions i on t.interception_id = i.id\njoin users u on i.initiator_id = u.id\nwhere $__timeFilter(i.started_at)\n  AND u.username ~ '$${username:regex}'\n  AND i.provider ~ '$${provider:regex}'\n  AND i.model ~ '$${model:regex}'\ngroup by u.username\norder by input desc"
    }
   ]
  },
  {
   "title": "Total usage for $username",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(t.input_tokens) as input,\nsum(t.output_tokens) as output,\nsum(\n  COALESCE(\n    t.metadata->>'cache_read_input', -- Anthropic\n    t.metadata->>'prompt_cached'     -- OpenAI\n  )::int\n) AS cache_read_input,\nsum((t.metadata->>'cache_creation_input')::int) AS cache_creation_input -- Anthropic\nfrom aibridge_token_usages t\njoin aibridge_interceptions i on t.interception_id = i.id\njoin users u on i.initiator_id = u.id\nwhere $__timeFilter(i.started_at)\n  AND u.username ~ '$${username:regex}'\n  AND i.provider ~ '$${provider:regex}'\n  AND i.model ~ '$${model:regex}'\norder by input desc"
    }
   ]
  },
  { "title": "Interceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Interceptions over time by user",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n$__timeGroupAlias(i.started_at, $__interval, NULL),\ncount(i.id) AS value,\nu.username AS metric\nFROM aibridge_interceptions i\njoin users u ON i.initiator_id = u.id\nWHERE\n$__timeFilter(i.started_at)\nAND u.username ~ '$${username:regex}'\nAND i.provider ~ '$${provider:regex}'\nAND i.model ~ '$${model:regex}'\nGROUP BY u.username, $__timeGroup(i.started_at, $__interval)\nORDER BY $__timeGroup(i.started_at, $__interval)"
    }
   ]
  },
  {
   "title": "Total interceptions",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aibridge_interceptions\nWHERE started_at > $__timeFrom() AND started_at <= $__timeTo()\nAND provider ~ '$${provider:regex}'\nAND model ~ '$${model:regex}'"
    }
   ]
  },
  { "title": "Prompts & tool calls details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "User Prompts",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT i.id,\n       u.username,\n       i.provider,\n       i.model,\n       p.prompt,\n       p.created_at\nFROM aibridge_user_prompts p\nJOIN aibridge_interceptions i ON p.interception_id = i.id\nJOIN users u ON i.initiator_id = u.id\nWHERE $__timeFilter(i.started_at)\n  AND u.username ~ '$${username:regex}'\n  AND i.provider ~ '$${provider:regex}'\n  AND i.model ~ '$${model:regex}'\nORDER BY p.created_at DESC;"
    }
   ]
  },
  {
   "title": "Tool Calls",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "select i.id, u.username, i.provider, i.model, t.server_url, t.tool, t.input, t.invocation_error, t.created_at FROM aibridge_tool_usages t\njoin aibridge_interceptions i ON t.interception_id = i.id\njoin users u on i.initiator_id = u.id\nwhere $__timeFilter(i.started_at)\nAND u.username ~ '$${username:regex}'\nAND i.provider ~ '$${provider:regex}'\nAND i.model ~ '$${model:regex}'\norder by t.created_at desc"
    }
   ]
  }
 ]
}