{
 "title": "Coder Control Plane",
 "time": { "from": "now-${DASHBOARD_TIMERANGE}", "to": "now" },
 "refresh": "${DASHBOARD_REFRESH}",
 "panels": [
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{ ${CODERD_SELECTOR} } == 1) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "(count(up{ ${CODERD_SELECTOR} } == 0) or vector(0)) > 0",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "One or more replicas are required to be running in order to serve the control-plane.\n\nSee [High Availability](https://coder.com/docs/v2/latest/admin/high-availability) for details on how to\nrun multiple `coderd` replicas."
   }
  },
  {
   "title": "Enterprise License",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(coderd_license_user_limit_enabled)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "(\n  max(coderd_license_active_users) / max(coderd_license_limit_users)\n) > 0",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "If you would like to try Coder's [Enterprise features](https://coder.com/docs/v2/latest/enterprise), you can [request a trial license](https://coder.com/docs/v2/latest/faqs#how-do-i-add-an-enterprise-license)."
   }
  },
  {
   "title": "CPU Usage Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{ ${CODERD_SELECTOR} }[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{ ${CODERD_SELECTOR}, resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{ ${CODERD_SELECTOR}, resource=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": {
    "content": "The cumulative CPU used per core-second. If `coderd` was using a full CPU core, that would be represented as 1 second.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "Terminations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (reason) (\n  count_over_time(kube_pod_container_status_terminated_reason{ ${CODERD_SELECTOR} }[$__interval])\n)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{ ${CODERD_SELECTOR} }[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": {
    "content": "Pods can be terminated for several reasons:\n- `OOMKilled`: pod exceeded its defined memory limit or was terminated by the OS for using excessive memory (if no limit defined)\n- `Error`: usually attributeable to a configuration problem\n- `Evicted`: pod has been evicted from node for overusing resources and will be rescheduled on another node is possible"
   }
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{ ${CODERD_SELECTOR} })",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{ ${CODERD_SELECTOR}, resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{ ${CODERD_SELECTOR}, resource=\"memory\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "options": {
    "content": "This shows the total memory used by each `coderd` container; it is the same metric which the [OOM killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html) uses.\n\nRequests & limits are shown if set."
   }
  },
  {
   "title": "Pubsub Latency (Median)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, coder_pubsub_send_latency_seconds)",
     "legendFormat": "Send"
    },
    {
     "expr": "quantile(0.5, coder_pubsub_receive_latency_seconds)",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Pubsub Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(coder_pubsub_latency_measure_errs_total[$__range]))\n  / count(coder_pubsub_latency_measure_errs_total)\n) or vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "options": {
    "content": "`coderd` uses Postgres for passing messages between subcomponents for coordination and signalling;\nthis is called \"pubsub\" (or publish-subscribe).\n\nWe measure the time for messages to be sent and received. Latencies higher than 500ms will likely lead to\nyour Coder deployment feeling sluggish. High latency is usually an indication that your Postgres server is under-resourced on CPU.\n\nHigh values for median should be concerning,\nwhile the 90th percentile shows the outliers."
   }
  },
  {
   "title": "Pubsub Latency (P90)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.9, coder_pubsub_send_latency_seconds)",
     "legendFormat": "Send"
    },
    {
     "expr": "quantile(0.9, coder_pubsub_receive_latency_seconds)",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(coderd_api_requests_processed_total{ ${CODERD_SELECTOR} }[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "options": {
    "content": "This shows the number of requests per second each `coderd` replica is handling.\n\nHeavy skewing towards a single `coderd` replica indicates faulty loadbalancing."
   }
  }
 ]
}