{
 "title": "Coder Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coder Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{ ${CODERD_SELECTOR} } == 1) or vector(0) > 0",
     "legendFormat": "Up"
    },
    {
     "expr": "count(up{ ${CODERD_SELECTOR} } == 0) or vector(0) > 0",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Provisioners",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coderd_provisionerd_num_daemons{ ${CODERD_SELECTOR} })",
     "legendFormat": "Built-in"
    },
    {
     "expr": "sum(coderd_provisionerd_num_daemons{ ${PROVISIONERD_SELECTOR} })",
     "legendFormat": "External"
    }
   ]
  },
  {
   "title": "Workspace Builds",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (status) (increase(coderd_provisionerd_job_timings_seconds_count{pod!=``}[$__range])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Running Workspaces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\", ${WORKSPACES_SELECTOR}} == 1)\nor\nsum(max by (workspace_owner, template_name, template_version) (coderd_workspace_latest_build_status{status=\"succeeded\", workspace_transition=\"start\"}))\nor\nvector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage High Watermark (Cumulative)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    max_over_time(\n        rate(container_cpu_usage_seconds_total{ ${CODERD_SELECTOR} }[1h:1m])\n        [$__range:]\n    )\n)",
     "legendFormat": "Control Plane CPU"
    },
    {
     "expr": "sum(\n    max_over_time(\n        rate(container_cpu_usage_seconds_total{ ${PROVISIONERD_SELECTOR} }[1h:1m])\n        [$__range:]\n    )\n)",
     "legendFormat": "Provisioner CPU"
    },
    {
     "expr": "sum(\n    max_over_time(\n        container_memory_working_set_bytes{ ${CODERD_SELECTOR} }\n        [$__range:]\n    )\n)",
     "legendFormat": "Control Plane RAM"
    },
    {
     "expr": "sum(\n    max_over_time(\n        container_memory_working_set_bytes{ ${PROVISIONERD_SELECTOR} }\n        [$__range:]\n    )\n)",
     "legendFormat": "Provisioner RAM"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(pg_up) or vector(0)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Observability Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"${PROMETHEUS_JOB}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Write Path",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"${LOKI_JOB}/write\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Read Path",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"${LOKI_JOB}/read\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Backend",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"${LOKI_JOB}/backend\", container=\"loki\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Canary",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"${LOKI_JOB}/canary\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Agent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"${GRAFANA_AGENT_JOB}\"}) or vector(0)",
     "legendFormat": "Current"
    },
    {
     "expr": "count(up{job=\"${GRAFANA_AGENT_JOB}\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Prometheus Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=\"${PROMETHEUS_JOB}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(loki_runtime_config_last_reload_successful) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Agent Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(agent_config_last_load_successful{job=\"${GRAFANA_AGENT_JOB}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    prometheus_tsdb_wal_storage_size_bytes{job=\"${PROMETHEUS_JOB}\"} +\n    prometheus_tsdb_storage_blocks_bytes{job=\"${PROMETHEUS_JOB}\"} +\n    prometheus_tsdb_symbol_table_size_bytes{job=\"${PROMETHEUS_JOB}\"}\n)\n/\nprometheus_tsdb_retention_limit_bytes{job=\"${PROMETHEUS_JOB}\"}",
     "legendFormat": "Retention limit used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"${HELM_NAMESPACE}\", resource=\"cpu\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(\n    max_over_time(\n        rate(container_cpu_usage_seconds_total{namespace=\"${HELM_NAMESPACE}\"}[$__rate_interval])\n        [$__range:]\n    )\n)",
     "legendFormat": "High Watermark"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"${HELM_NAMESPACE}\", resource=\"memory\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(\n    max_over_time(container_memory_working_set_bytes{namespace=\"${HELM_NAMESPACE}\"}[$__range])\n)",
     "legendFormat": "High Watermark"
    }
   ]
  }
 ]
}