apiVersion: v2
name: coder
description: A Helm chart for Kubernetes with Coder and auxillary resources.
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: coder
    version: v2.35.1
    repository: "https://helm.coder.com/v2"
    alias: coder