apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}.aws
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extra.secretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.extra.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.extra.secretStore.aws.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}.secrets
  namespace: {{ .Release.Namespace }}
  {{- with (index .Values "postgres-exporter").passwordSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (index .Values "postgres-exporter").passwordSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}.secrets
    kind: SecretStore
  refreshPolicy: {{ (index .Values "postgres-exporter").passwordSecret.refreshPolicy }}
  refreshInterval: {{ (index .Values "postgres-exporter").passwordSecret.refreshInterval }}
  target:
    name: {{ (index .Values "postgres-exporter").passwordSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ (index .Values "postgres-exporter")passwordSecret.secretArn }}
        metadataPolicy: None