extra:
  service:
    enable: true
    labels: {}
    annotations: {}
    loadBalancerClass: "service.k8s.aws/nlb"
  prometheus:
    enable: true
    labels: {}
    annotations: {}
  certificate:
    enable: true
    name: certificate
    labels: {}
    annotations: {}
    commonName: ""
    dnsNames: []
    duration: 2160h
    renewBefore: 360h
    issuerRef:
      kind: ClusterIssuer
      name: issuer
