apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}.aws
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extra.secretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.extra.secretStore.annotations }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.extra.secretStore.aws.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}.cloudflare
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}.aws
    kind: SecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h0m0s"
  target:
    name: {{ .Values.extra.defaultIssuer.acme.cloudflare.apiTokenSecretRef.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template: 
      type: Opaque
      metadata:
        labels: 
        annotations:
      data:
        - secretKey: {{ .Values.extra.defaultIssuer.acme.cloudflare.apiTokenSecretRef.key }}
          remoteRef:
            key: {{ .Values.extra.defaultIssuer.acme.cloudflare.apiTokenSecretRef.name }}
            property: {{ .Values.extra.defaultIssuer.acme.cloudflare.apiTokenSecretRef.key }}