{
 "title": "Coder Workspaces",
 "time": { "from": "now-${DASHBOARD_TIMERANGE}", "to": "now" },
 "refresh": "${DASHBOARD_REFRESH}",
 "templating": {
  "list": [
   {
    "name": "workspace_name",
    "label": "Workspace Name Filter",
    "query": {
     "query": "label_values(coderd_workspace_builds_total,workspace_name)"
    }
   },
   {
    "name": "template_name",
    "label": "Template Name Filter",
    "query": {
     "query": "label_values(coderd_workspace_builds_total,template_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1.2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<small>**HINT**: use the dropdowns above to filter by specific workspaces and/or templates.</small>"
   }
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1.2 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 2.2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{ ${WORKSPACES_SELECTOR} }[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 2.2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{ ${WORKSPACES_SELECTOR} })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2.2 },
   "options": {
    "content": "The cumulative CPU used per core-second. If a workspace was using a full CPU core, that would be represented as 1 second.\n\nSee the Kubernetes [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units) for more details.\n\nThe total memory used by each workspace container is represented; it is the same metric which the [OOM killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html) uses."
   }
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10.2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  round(increase(kube_pod_container_status_restarts_total{ ${WORKSPACES_SELECTOR} }[$__interval]))\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10.2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, reason) (\n  count_over_time(kube_pod_container_status_terminated_reason{ ${WORKSPACES_SELECTOR} }[$__interval])\n)",
     "legendFormat": "{{pod}}:{{reason}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10.2 },
   "options": {
    "content": "Pods can be terminated for several reasons:\n- `OOMKilled`: pod exceeded its defined memory limit or was terminated by the OS for using excessive memory (if no limit defined)\n- `Error`: usually attributeable to a configuration problem\n- `Evicted`: pod has been evicted from node for overusing resources and will be rescheduled on another node is possible\n\nPod restarts are not necessarily problematic, but they are worth noting."
   }
  },
  { "title": "Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18.2 } },
  {
   "title": "Successful Builds by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_transition) (\n    (\n      # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n      # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n      (\n        coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n        coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n      ) >= 0) \n      or coderd_workspace_builds_total{status=\"success\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful Builds by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 19.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_transition) (\n    (\n      # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n      # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n      (\n        coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n        coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n      ) >= 0) \n      or coderd_workspace_builds_total{status=\"failed\", workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19.2 },
   "options": {
    "content": "Workspaces \"transition\" between `STOP`, `START`, and `DESTROY` states.\n\nWorkspaces transition between states when a \"build\" is initiated, which is an execution of `terraform` against the chosen template.\n\nUse the \"Build Count\" table to identify workspace owners which may be struggling with template builds, in order to proactively reach out to them with assistance.\n\nConsult the [Template documentation](https://coder.com/docs/v2/latest/templates) for more information."
   }
  },
  {
   "title": "Build Log",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 27.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workspace_name, workspace_owner, status, template_name, template_version, workspace_transition) (\n  # Since new series are created and are initially set to a value of 1, we cannot use \"increase\" (because an increase from <nothing> to 1 does not yield 1).\n  # So we compare the current series to an interval ago to see if we have any new series and then sum the series we find. \n  ((\n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} - \n    coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"} offset $__interval\n  ) >= 0) \n  or coderd_workspace_builds_total{workspace_name=~\"$workspace_name\", template_name=~\"$template_name\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 27.2 },
   "options": {
    "content": "This table shows a reverse-chronological log of all workspace builds.\n\nThe \"Count\" field shows the count of events which occurred within a minute, grouped by all columns."
   }
  },
  {
   "title": "Workspace by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (workspace_owner) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace by User/Template",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (workspace_owner, template_name) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "{{workspace_owner}}:{{template_name}}"
    }
   ]
  },
  {
   "title": "Template Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (template_name) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Template Version Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 37.2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (template_name, template_version) (coderd_workspace_latest_build_status{template_name=~\"$template_name\"})",
     "legendFormat": "{{template_name}}:{{template_version}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 37.2 },
   "options": {
    "content": "These charts show the distribution of workspaces and templates.\n\nUse these charts to identify which users have outdated templates, and which templates are the most/least popular in your organisation."
   }
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44.2 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 45.2 },
   "targets": [
    {
     "expr": "{ ${NON_WORKSPACES_SELECTOR}, logger=~\"(.*runner|terraform|provisioner.*)\"} |~ \"$workspace_name\" or \"$template_name\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 45.2 },
   "options": {
    "content": "These are the logs produced by the [Provisioners](/d/provisionerd/provisioners?$${__url_time_range}).\n\nUse the dropdowns at the top to filter the logs down to a specific workspace and/or template."
   }
  }
 ]
}