apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
    service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  finalizers:
  - service.k8s.aws/resources
  labels:
    app.kubernetes.io/instance: coder
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: coder
    app.kubernetes.io/version: 2.25.1
    helm.sh/chart: coder-2.25.1
  name: coder
  namespace: coder
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.92.166
  clusterIPs:
  - 172.20.92.166
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: http
    nodePort: 32579
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31589
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: coder
    app.kubernetes.io/name: coder
  sessionAffinity: None
  type: LoadBalancer
