apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}.aws
  namespace: {{ .Release.Namespace }}
  {{- with .Values.provisionerDaemon.secretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.provisionerDaemon.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.provisionerDaemon.secretStore.aws.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}.secrets
  namespace: {{ .Release.Namespace }}
  {{- with .Values.provisionerDaemon.secrets.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.provisionerDaemon.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}.aws
    kind: SecretStore
  refreshPolicy: {{ .Values.provisionerDaemon.secrets.refreshPolicy }}
  refreshInterval: {{ .Values.provisionerDaemon.secrets.refreshInterval }}
  target:
    name: {{ .Values.provisionerDaemon.keySecretName | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.provisionerDaemon.secrets.secretArn }}
        metadataPolicy: None
